version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: senha
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


